Repository KMU-FlowERD/front-end, pull requests merged in 2024-09, with the labels that each got.

#2 chore: add templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .idea/.gitignore
  .idea/flow-erd.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  jest.config.ts
Labels: documentation

#7 chore: Add `ESLint` and `Prettier`
  .eslintrc.json
  .prettierrc
  eslint.config.mjs
  jest.config.ts
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  tsconfig.json
Labels: Setting

#12 chore: Add `Emotion`
  package-lock.json
  package.json
Labels: Setting

#13 chore: Add `Axios`
  package-lock.json
  package.json
Labels: Setting

#14 chore: Add `Zustand`
  package-lock.json
  package.json
Labels: Setting

#15 chore: install `jest`
  .eslintrc.json
  eslint.config.mjs
  jest.config.ts
  package-lock.json
  package.json
  src/__tests__/jest.test.ts
Labels: Setting

#17 chore: install `TanStack Query`, `RxJS`, `classnames`
  .eslintrc.json
  package-lock.json
  package.json
  src/app/layout.tsx
  src/providers/TanStackQueryProvider.tsx
  src/providers/index.ts
Labels: Setting

#21 feat: basic ERD project page styling
  .eslintrc.json
  src/app/globals.css
  src/app/page.tsx
  src/components/ErdDrawTools.tsx
  src/components/RelationshipMenu.tsx
  src/components/Table.tsx
  src/components/TableMenu.tsx
  src/components/implements-icon/ArrowIcon.tsx
  src/components/implements-icon/MemoIcon.tsx
  src/components/implements-icon/PointerIcon.tsx
  src/components/implements-icon/RelationshipIcons.tsx
  src/components/implements-icon/TableIcon.tsx
  src/components/implements-icon/icon.type.ts
  src/components/implements-icon/index.ts
  src/components/index.ts
  src/page/erd-project.page.tsx
  src/page/index.ts
Labels: Feature, Help wanted, UI/UX
