Repository KMU-FlowERD/front-end, pull requests merged in 2024-10, with the labels that each got.

#23 feat: Implement state and actions to manage ERD data
  .eslintrc.json
  package-lock.json
  package.json
  src/__tests__/erd-project.slice.test.ts
  src/__tests__/jest.test.ts
  src/features/erd-project/erd-project.slice.ts
  src/features/erd-project/index.ts
Labels: Feature, Test

#25 chore: add linting and formatting workflow
  .eslintrc.json
  .github/workflows/lint-format.yml
  .prettierrc
  jest.config.ts
  package.json
  src/app/page.module.css
Labels: Setting

#27 chore: add run tests workflow
  .github/workflows/run-test.yml
Labels: Setting

#28 [FLOW-12] feat: connect ERD state, action and UI
  src/components/ConnectLine.tsx
  src/components/ErdDrawTools.tsx
  src/components/Relationship.tsx
  src/components/RelationshipInformation.tsx
  src/components/Table.tsx
  src/components/TableInformation.tsx
  src/components/column-edit/ColumnEditMenu.tsx
  src/components/column-edit/Columns.tsx
  src/components/column-edit/FkColumns.tsx
  src/components/column-edit/PkColumns.tsx
  src/components/column-edit/PkFkColumns.tsx
  src/components/column-edit/index.ts
  src/components/implements-icon/ArrowIcon.tsx
  src/components/implements-icon/IdentifyManyToManyIcon.tsx
  src/components/implements-icon/IdentifyOneToManyIcon.tsx
  src/components/implements-icon/IdentifyOneToOneIcon.tsx
  src/components/implements-icon/MemoIcon.tsx
  src/components/implements-icon/MenuIcon.tsx
  src/components/implements-icon/NonIdentifyManyToManyIcon.tsx
  src/components/implements-icon/NonIdentifyOneToManyIcon.tsx
  src/components/implements-icon/NonIdentifyOneToOneIcon.tsx
  src/components/implements-icon/PointerIcon.tsx
  src/components/implements-icon/RelationshipIcons.tsx
  src/components/implements-icon/TableIcon.tsx
  src/components/implements-icon/icon.type.ts
  src/components/implements-icon/index.ts
  src/components/index.ts
  src/components/table/Columns.tsx
  src/components/table/Table.tsx
  src/components/table/TableMenu.tsx
  src/components/table/index.ts
  src/features/draw-tools/draw-tools.slice.ts
  src/features/draw-tools/index.ts
  src/features/erd-project/erd-project.slice.ts
  src/features/table-mapping/index.ts
  src/features/table-mapping/table-mapping.helper.ts
  src/features/table-mapping/table-mapping.type.ts
  src/page/erd-project.page.tsx
Labels: Feature, UI/UX

#29 [FLOW-3] feat: add IDEF1X notation
  src/__tests__/erd-project.slice.test.ts
  src/components/ConnectLine.tsx
  src/components/ErdDrawTools.tsx
  src/components/Relationship.tsx
  src/components/implements-icon/ArrowIcon.tsx
  src/components/implements-icon/MemoIcon.tsx
  src/components/implements-icon/PointerIcon.tsx
  src/components/implements-icon/RelationshipIcons.tsx
  src/components/implements-icon/TableIcon.tsx
  src/features/draw-tools/draw-tools.slice.ts
  src/features/erd-project/erd-project.slice.ts
  src/features/table-mapping/table-mapping.helper.ts
  src/features/table-mapping/table-mapping.type.ts
  src/page/erd-project.page.tsx
Labels: Feature, UI/UX

#32 [FLOW-1] fix: update relation multiplicity for foreign key columns
  src/__tests__/erd-project.slice.test.ts
  src/features/erd-project/erd-project.slice.ts
Labels: Bug, Fix

#34 [FLOW-18] refactor: modify to use useERDProjectStore instead of useStore
  src/app/layout.tsx
  src/page/erd-project.page.tsx
  src/providers/ERDProjectProvider.tsx
  src/providers/index.ts
Labels: Feature, Refactor

#33 [FLOW-19] refactor: update ERDRelation type
  src/features/erd-project/erd-project.slice.ts
Labels: Feature, Refactor

#35 [FLOW-20] fix: apply some type changes
  src/__tests__/erd-project.slice.test.ts
  src/features/erd-project/erd-project.slice.ts
Labels: Bug, Fix

#36 [FLOW-21] fix: resolve issue that related to KeyType
  src/components/column-edit/ColumnEditMenu.tsx
  src/components/table/Table.tsx
  src/page/erd-project.page.tsx
Labels: Refactor, Fix

#31 [FLOW-13] feat: add relation delete and nullable menu
  src/components/ConnectLine.tsx
  src/components/Relationship.tsx
  src/components/RelationshipMenu.tsx
  src/components/column-edit/ColumnEditMenu.tsx
  src/components/column-edit/Columns.tsx
  src/components/column-edit/FkColumns.tsx
  src/components/column-edit/PkColumns.tsx
  src/components/column-edit/PkFkColumns.tsx
  src/components/table/Table.tsx
  src/components/table/TableMenu.tsx
  src/features/mapping/index.ts
  src/features/mapping/mapping.helper.ts
  src/features/mapping/mapping.hook.ts
  src/features/mapping/mapping.type.ts
  src/features/table-mapping/index.ts
  src/page/erd-project.page.tsx
  src/providers/MappingProvider.tsx
Labels: Feature, UI/UX

#38 [FLOW-25] chore: install husky
  .husky/commit-msg
  .husky/commit-msg.js
  package-lock.json
  package.json
Labels: Setting

#39 [FLOW-23] feat: add useModal, useModalContext hooks, implement ProfileSetting component with mockup data
  src/app/setting/page.tsx
  src/components/home/setting/ProfileInformation.tsx
  src/components/home/setting/ProfileSetting.styles.ts
  src/components/home/setting/ProfileSetting.tsx
  src/components/home/setting/index.ts
  src/components/home/sidebar/Sidebar.styles.ts
  src/components/home/sidebar/Sidebar.tsx
  src/features/modal/index.ts
  src/features/modal/modal.hook.tsx
Labels: Feature, UI/UX

#40 [FLOW-6] feat: add update canvas size and scroll using drag
  src/app/globals.css
  src/app/page.tsx
  src/components/ErdDrawTools.tsx
  src/components/RelationshipInformation.tsx
  src/components/TableInformation.tsx
  src/components/table/Table.tsx
  src/features/erd-page/erd-project-page.hook.ts
  src/features/erd-page/index.ts
  src/features/mapping/mapping.hook.ts
  src/page/erd-project.page.tsx
Labels: Feature, Refactor, UI/UX

#43 [FLOW-24] feat: add many to many mapping
  src/page/erd-project/erd-project.page.styles.ts
  src/page/erd-project/erd-project.page.tsx
Labels: Feature

#44 [FLOW-32] refactor: table refactor using custom hook and provider
  src/components/column-edit/ColumnEditMenu.tsx
  src/components/table/Table.tsx
  src/components/table/TableMenu.tsx
  src/features/erd-page/erd-page.table.hook.ts
  src/providers/TableProvider.tsx
Labels: Refactor
